// <auto-generated />
using System;
using ApiMovil.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiMovil.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiMovil.Models.Empleado", b =>
                {
                    b.Property<int>("IdEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpleado"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEmpleado");

                    b.ToTable("Empleados");

                    b.HasData(
                        new
                        {
                            IdEmpleado = 1,
                            Apellidos = "Admin",
                            Correo = "misael@cibertec.com",
                            DNI = "12345678",
                            Estado = true,
                            Nombres = "Misael",
                            Telefono = "999888777"
                        });
                });

            modelBuilder.Entity("ApiMovil.Models.Horario", b =>
                {
                    b.Property<int>("IdHorario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHorario"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("HoraEntrada")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("HoraFinRefrigerio")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("HoraRefrigerio")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraSalida")
                        .HasColumnType("time");

                    b.Property<string>("NombreHorario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ToleranciaMinutos")
                        .HasColumnType("int");

                    b.HasKey("IdHorario");

                    b.ToTable("Horarios");
                });

            modelBuilder.Entity("ApiMovil.Models.Marcacion", b =>
                {
                    b.Property<int>("IdMarcacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMarcacion"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("date");

                    b.Property<TimeSpan?>("FinDescanso")
                        .HasColumnType("time");

                    b.Property<string>("Foto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("HoraEntrada")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("HoraSalida")
                        .HasColumnType("time");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("InicioDescanso")
                        .HasColumnType("time");

                    b.Property<decimal?>("Latitud")
                        .HasColumnType("decimal(18, 7)");

                    b.Property<decimal?>("Longitud")
                        .HasColumnType("decimal(18, 7)");

                    b.HasKey("IdMarcacion");

                    b.HasIndex("IdEmpleado");

                    b.ToTable("Marcaciones");
                });

            modelBuilder.Entity("ApiMovil.Models.Planificacion", b =>
                {
                    b.Property<int>("IdPlanificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPlanificacion"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<int>("IdTurno")
                        .HasColumnType("int");

                    b.HasKey("IdPlanificacion");

                    b.HasIndex("IdEmpleado");

                    b.HasIndex("IdTurno");

                    b.ToTable("Planificaciones");
                });

            modelBuilder.Entity("ApiMovil.Models.Turno", b =>
                {
                    b.Property<int>("IdTurno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTurno"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<int?>("IdHorarioDomingo")
                        .HasColumnType("int");

                    b.Property<int?>("IdHorarioJueves")
                        .HasColumnType("int");

                    b.Property<int?>("IdHorarioLunes")
                        .HasColumnType("int");

                    b.Property<int?>("IdHorarioMartes")
                        .HasColumnType("int");

                    b.Property<int?>("IdHorarioMiercoles")
                        .HasColumnType("int");

                    b.Property<int?>("IdHorarioSabado")
                        .HasColumnType("int");

                    b.Property<int?>("IdHorarioViernes")
                        .HasColumnType("int");

                    b.Property<string>("NombreTurno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdTurno");

                    b.HasIndex("IdHorarioDomingo");

                    b.HasIndex("IdHorarioJueves");

                    b.HasIndex("IdHorarioLunes");

                    b.HasIndex("IdHorarioMartes");

                    b.HasIndex("IdHorarioMiercoles");

                    b.HasIndex("IdHorarioSabado");

                    b.HasIndex("IdHorarioViernes");

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("ApiMovil.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Usuario");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdEmpleado");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            IdUsuario = 1,
                            Clave = "123456",
                            Estado = true,
                            IdEmpleado = 1,
                            Rol = "Administrador",
                            UsuarioNombre = "misael@cibertec.com"
                        });
                });

            modelBuilder.Entity("ApiMovil.Models.Marcacion", b =>
                {
                    b.HasOne("ApiMovil.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("ApiMovil.Models.Planificacion", b =>
                {
                    b.HasOne("ApiMovil.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiMovil.Models.Turno", "Turno")
                        .WithMany()
                        .HasForeignKey("IdTurno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("ApiMovil.Models.Turno", b =>
                {
                    b.HasOne("ApiMovil.Models.Horario", "HorarioDomingo")
                        .WithMany()
                        .HasForeignKey("IdHorarioDomingo");

                    b.HasOne("ApiMovil.Models.Horario", "HorarioJueves")
                        .WithMany()
                        .HasForeignKey("IdHorarioJueves");

                    b.HasOne("ApiMovil.Models.Horario", "HorarioLunes")
                        .WithMany()
                        .HasForeignKey("IdHorarioLunes");

                    b.HasOne("ApiMovil.Models.Horario", "HorarioMartes")
                        .WithMany()
                        .HasForeignKey("IdHorarioMartes");

                    b.HasOne("ApiMovil.Models.Horario", "HorarioMiercoles")
                        .WithMany()
                        .HasForeignKey("IdHorarioMiercoles");

                    b.HasOne("ApiMovil.Models.Horario", "HorarioSabado")
                        .WithMany()
                        .HasForeignKey("IdHorarioSabado");

                    b.HasOne("ApiMovil.Models.Horario", "HorarioViernes")
                        .WithMany()
                        .HasForeignKey("IdHorarioViernes");

                    b.Navigation("HorarioDomingo");

                    b.Navigation("HorarioJueves");

                    b.Navigation("HorarioLunes");

                    b.Navigation("HorarioMartes");

                    b.Navigation("HorarioMiercoles");

                    b.Navigation("HorarioSabado");

                    b.Navigation("HorarioViernes");
                });

            modelBuilder.Entity("ApiMovil.Models.Usuario", b =>
                {
                    b.HasOne("ApiMovil.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });
#pragma warning restore 612, 618
        }
    }
}
